### ISSUE TITLE
Lack of  `prev_obs` in `SmartRandomAgent*`

### ISSUE THREAD

**Issue by terryzhao127** [BorealisAI/pommerman-baseline#2]
First of all, thanks for sharing!

However, I failed to run your `SmartRandomAgent*`. I found there is a parameter called `prev_obs` in `get_filtered_actions`, which is syntactically a optional parameter but [accessed inside the function](https://github.com/BorealisAI/pommerman-baseline/blob/112a202b0d46a3a5a47e904630359db15e8896e2/action_prune.py#L319).

So, what is the exact definition of `prev_obs` and is it necessary, if it is, how to use it?

**Comment by terryzhao127** [comment]
I changed codes of `SmartRandomAgent` and it worked:

```python
class SmartRandomAgent(BaseAgent):
    """ random with filtered actions"""
    def __init__(self):
        super(SmartRandomAgent, self).__init__()

        self.step = 0
        self.observations = []

    def act(self, obs, action_space):
        self.step += 1

        if self.step <= 2:
            self.observations.append(copy.deepcopy(obs))
            return Action.Stop

        self.observations = self.observations[1:]
        self.observations.append(copy.deepcopy(obs))

        valid_actions = action_prune.get_filtered_actions(obs, self.observations)

        if len(valid_actions) == 0:
            return Action.Stop

        return random.choice(valid_actions)
```

Do I need create a pull request, or you guys please update your codes?

If these codes did what exactly you guys try to let the agent do, is it a bit weird to stop for two steps?

**Comment by b-kartal** [comment]
Hello,
Pommerman simulator does not provide information about moving bombs with agent observations. The filter uses two consecutive frames (like optical flow) to determine moving bombs. We considered the impact of initial wait would be negligible as agents start at isolated corners. Please create a pull request, and we will check. 
Thanks!

**Comment by cgao3** [comment]
The argument is prev_two_obs, i.e. a tuple of size 2,  you can use
`valid_actions = action_prune.get_filtered_actions(obs, (None,None))` to bypass this feature.. 

This is used to deal with flame problem, i.e., if there is a flame at position x in current step, will the flame go away in t+1?  Because the environment does not provide flame's remaining life, while it defines flame has life of 2, so if a flame is at position x both current and previous observations, then it may sound reasonable to derive that at t+1, the flame will disappear. But there is one issue, what if the flame is a "overlap" of multiple bombs exploded at different times?  To counter this problem, previous previous status on that cell is also required.  So two previous observations are needed. 

To use this feature, you need to keep track of the last two previous observations in your agent. 

`prev_two_obs[0]` is the previous previous observation
`prev_two_obs[1]` is the previous observation.

**Comment by terryzhao127** [comment]
Ah, I see. Thanks.

**Comment by terryzhao127** [comment]
By the way, would you like to opensource your paper [Using Monte Carlo Tree Search as a Demonstrator within Asynchronous Deep RL](https://arxiv.org/abs/1812.00045)? I find it interesting that it combines MCTS and A3C.

**Comment by b-kartal** [comment]
> By the way, would you like to opensource your paper [Using Monte Carlo Tree Search as a Demonstrator within Asynchronous Deep RL](https://arxiv.org/abs/1812.00045)? I find it interesting that it combines MCTS and A3C.

We plan to open-source it in the future, but not necessarily near term. Thanks for the interest.
